version: "3.9"
services:
  pulsar:
    hostname: pulsar
    image: apachepulsar/pulsar:2.9.0
    command: bin/pulsar standalone --advertised-address pulsar
  spout:
    image: raphtory-lotr
    environment:
      COMPONENT: spout
      RAPHTORY_PULSAR_BROKER_ADDRESS: "pulsar://pulsar:6650"
      RAPHTORY_PULSAR_ADMIN_ADDRESS: "http://pulsar:8080"
      RAPHTORY_ZOOKEEPER_ADDRESS: "pulsar:2181"
      RAPHTORY_QUERY_ADDRESS: query
  builder:
    image: raphtory-lotr
    environment:
      COMPONENT: builder
      RAPHTORY_PULSAR_BROKER_ADDRESS: "pulsar://pulsar:6650"
      RAPHTORY_PULSAR_ADMIN_ADDRESS: "http://pulsar:8080"
      RAPHTORY_ZOOKEEPER_ADDRESS: "pulsar:2181"
      RAPHTORY_QUERY_ADDRESS: query
  query:
    image: raphtory-lotr
    hostname: query
    environment:
      COMPONENT: querymanager
      RAPHTORY_PULSAR_BROKER_ADDRESS: "pulsar://pulsar:6650"
      RAPHTORY_PULSAR_ADMIN_ADDRESS: "http://pulsar:8080"
      RAPHTORY_ZOOKEEPER_ADDRESS: "pulsar:2181"
      RAPHTORY_QUERY_ADDRESS: query
  partition:
    image: raphtory-lotr
    hostname: partition
    environment:
      COMPONENT: partitionmanager
      RAPHTORY_PULSAR_BROKER_ADDRESS: "pulsar://pulsar:6650"
      RAPHTORY_PULSAR_ADMIN_ADDRESS: "http://pulsar:8080"
      RAPHTORY_ZOOKEEPER_ADDRESS: "pulsar:2181"
      RAPHTORY_QUERY_ADDRESS: query
    volumes:
      - "/tmp/raphtory:/tmp/raphtory"
  client:
    image: raphtory-lotr
    hostname: client
    environment:
      COMPONENT: client
      RAPHTORY_PULSAR_BROKER_ADDRESS: "pulsar://pulsar:6650"
      RAPHTORY_PULSAR_ADMIN_ADDRESS: "http://pulsar:8080"
      RAPHTORY_ZOOKEEPER_ADDRESS: "pulsar:2181"
      RAPHTORY_QUERY_ADDRESS: query
