version: "3.9"
services:
  pulsar:
    hostname: pulsar
    image: apachepulsar/pulsar:2.9.0
    command: bin/pulsar standalone --advertised-address pulsar
    healthcheck:
      test: curl -s http://pulsar:8080/admin/v2/worker/cluster
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  spout:
    image: raphtory-lotr
    environment:
      COMPONENT: spout
      RAPHTORY_PULSAR_BROKER_ADDRESS: "pulsar://pulsar:6650"
      RAPHTORY_PULSAR_ADMIN_ADDRESS: "http://pulsar:8080"
      RAPHTORY_ZOOKEEPER_ADDRESS: "pulsar:2181"
      RAPHTORY_QUERY_ADDRESS: query
    depends_on:
      pulsar:
        condition: service_healthy
  builder:
    image: raphtory-lotr
    environment:
      COMPONENT: builder
      RAPHTORY_PULSAR_BROKER_ADDRESS: "pulsar://pulsar:6650"
      RAPHTORY_PULSAR_ADMIN_ADDRESS: "http://pulsar:8080"
      RAPHTORY_ZOOKEEPER_ADDRESS: "pulsar:2181"
      RAPHTORY_QUERY_ADDRESS: query
    depends_on:
      pulsar:
        condition: service_healthy
  query:
    image: raphtory-lotr
    hostname: query
    environment:
      COMPONENT: querymanager
      RAPHTORY_PULSAR_BROKER_ADDRESS: "pulsar://pulsar:6650"
      RAPHTORY_PULSAR_ADMIN_ADDRESS: "http://pulsar:8080"
      RAPHTORY_ZOOKEEPER_ADDRESS: "pulsar:2181"
      RAPHTORY_QUERY_ADDRESS: query
    depends_on:
      pulsar:
        condition: service_healthy
  partition:
    image: raphtory-lotr
    hostname: partition
    environment:
      COMPONENT: partitionmanager
      RAPHTORY_PULSAR_BROKER_ADDRESS: "pulsar://pulsar:6650"
      RAPHTORY_PULSAR_ADMIN_ADDRESS: "http://pulsar:8080"
      RAPHTORY_ZOOKEEPER_ADDRESS: "pulsar:2181"
      RAPHTORY_QUERY_ADDRESS: query
    volumes:
      - "/tmp/raphtory:/tmp/raphtory"
    depends_on:
      pulsar:
        condition: service_healthy
  client:
    image: raphtory-lotr
    hostname: client
    environment:
      COMPONENT: client
      RAPHTORY_PULSAR_BROKER_ADDRESS: "pulsar://pulsar:6650"
      RAPHTORY_PULSAR_ADMIN_ADDRESS: "http://pulsar:8080"
      RAPHTORY_ZOOKEEPER_ADDRESS: "pulsar:2181"
      RAPHTORY_QUERY_ADDRESS: query
    depends_on:
      pulsar:
        condition: service_healthy
